# Generated by Django 3.1.1 on 2021-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
