# Generated by Django 3.1.1 on 2021-03-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20210309_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='www.notice')),
            ],
        ),
    ]
