# Generated by Django 3.1.1 on 2021-03-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_noticeattach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
    ]
